routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\YindulaCms\app\Http\Controllers\CmsEventController;
use Modules\YindulaCms\app\Http\Controllers\FeatureController;
use Modules\YindulaCms\app\Http\Controllers\PageSettingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('cms')->name('cms.')->group(function () {

    Route::middleware('auth')->group(function () {

        Route::get('/dashboard', 'YindulaCmsController@dashboard')->name('dashboard');

        Route::resource('banners', BannerController::class);
        Route::resource('categories', CategoryController::class);
        Route::resource('cmsSettings', CmsSettingController::class);

        Route::resource('posts', PostController::class);
        Route::resource('sliders', SliderController::class);
        Route::resource('cmsEvents', CmsEventController::class);

        Route::resource('galleries', GalleryController::class);
        Route::resource('menus', MenuController::class);

        /*
        |--------------------------------------------------------------------------
        | Pages
        |--------------------------------------------------------------------------|
        */
        Route::resource('pages', PageController::class);

        Route::post(
            'pages/setHomePage/{id}',
            [Modules\YindulaCms\app\Http\Controllers\PageController::class, 'setHomePage']
        )->name('pages.setHomePage');

        Route::post(
            'pages/setContactPage/{id}',
            [Modules\YindulaCms\app\Http\Controllers\PageController::class, 'setContactPage']
        )->name('pages.setContactPage');

        /*
        |--------------------------------------------------------------------------
        | Feature Sections
        |--------------------------------------------------------------------------|
        */
        Route::resource('featureSections', FeatureSectionController::class);

        Route::get('featureSectionsAdd/{pageId}', [
            FeatureSectionController::class, 'add'
        ])->name('featureSections.add');

        /*
        |--------------------------------------------------------------------------
        | Features
        |--------------------------------------------------------------------------|
        */
        Route::resource('features', FeatureController::class);
        Route::get('featuresAdd/{pageId}', [FeatureController::class, 'add'])->name('features.add');

        /*
        |--------------------------------------------------------------------------
        | Page Settings
        |--------------------------------------------------------------------------|
        */
        Route::resource('pageSettings', PageSettingController::class);

        Route::get('pageSettingsAdd/{pageId}', [
            PageSettingController::class, 'add'
        ])->name('pageSettings.add');

        Route::get('pageSettingsCreateOrEdit/{pageId}', [
            PageSettingController::class, 'createOrEdit'
        ])->name('pageSettings.createOrEdit');

        /*
        |==========================================================================|
        */
    });
});

app/Models/Banner.php
<?php

namespace Modules\YindulaCms\app\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Storage;
use Modules\YindulaCms\app\Traits\UsesCmsDatabaseConnection;
use Modules\YindulaCms\app\Traits\UsesDefaultConnection;
use Modules\YindulaCms\app\Utilities\BannerHelper;
use Modules\YindulaCms\app\Utilities\ModelMediaHelper;
use Modules\YindulaCore\Traits\CanGetTableNameStatically;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

/**
 * Class Banner
 * @package App\Models
 * @version September 10, 2022, 5:51 pm UTC
 *
 * @property string $title
 * @property string $excerpt
 * @property string $description
 * @property string $image
 * @property string $video
 * @property boolean $is_default
 * @property string $image_two
 */
class Banner extends Model
{

    use HasFactory, CanGetTableNameStatically, UsesCmsDatabaseConnection;

    public $table = 'banners';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'title',
        'excerpt',
        'description',
        'image',
        'video',
        'is_default',
        'image_two'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'title' => 'string',
        'excerpt' => 'string',
        'description' => 'string',
        'image' => 'string',
        'video' => 'string',
        'is_default' => 'boolean',
        'image_two' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'title' => 'required|string|max:100',
        'excerpt' => 'nullable|string',
        'description' => 'nullable|string',
        'image' => 'nullable|string|max:250',
        'video' => 'nullable|string|max:125',
        'is_default' => 'required|boolean',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'image_two' => 'nullable|string'
    ];




    public function getReadableVideoAttribute()
    {
        return env('APP_URL') .  (new Application($this->getVideoPath()))->replaceBackSlashesWithForwardSlashes();
    }


    private function getVideoPath()
    {
        if (App::environment('production')) {
            return '/storage/app/public/' . json_decode($this->attributes['video'])[0]->download_link;
        }
        return Storage::url(json_decode($this->attributes['video'])[0]->download_link);
    }

    /**
     *
     * @return string
     */
    public function getImageUrlAttribute(): string
    {
        return ModelMediaHelper::getImageAttribute(self::tableName(), $this->id);
    }

    /**
     *
     * @return string
     */
    public function getImageTwoUrlAttribute(): string
    {
        return ModelMediaHelper::getImageTwoAttribute(self::tableName(), $this->id);
    }
}

Livewire/BannersTable.php
<?php

namespace Modules\YindulaCms\Livewire;

use Laracasts\Flash\Flash;

use Livewire\Component;
use Modules\YindulaCms\app\Models\Banner;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;
use Rappasoft\LaravelLivewireTables\Views\Columns\BooleanColumn;
use Rappasoft\LaravelLivewireTables\Views\Columns\ImageColumn;

class BannersTable extends DataTableComponent
{
    protected $model = Banner::class;

    protected $listeners = ['deleteRecord' => 'deleteRecord'];

    public function deleteRecord($id)
    {
        Banner::find($id)->delete();
        Flash::success(__('messages.deleted', ['model' => __('models/banners.singular')]));
        $this->dispatch('refreshDatatable');
    }

    public function configure(): void
    {
        $this->setPrimaryKey('id');
    }

    public function columns(): array
    {
        return [
            Column::make(__('models/banners.fields.title'), "title")
                ->sortable()
                ->searchable(),

            ImageColumn::make(__('models/banners.fields.image'))
                ->location(function ($row) {
                    return asset($row->image_url);
                })
                ->attributes(function ($row) {
                    return [
                        'class' => 'img-fluid',
                        'style' => 'max-width: 100px; max-height: 100px;'
                    ];
                }),

            ImageColumn::make(__('models/banners.fields.image_two'))
            ->location(function ($row) {
                return asset($row->image_two_url);
            })
            ->attributes(function ($row) {
                return [
                    'class' => 'img-fluid',
                    'style' => 'max-width: 100px; max-height: 100px;'
                ];
            }),
            Column::make(__('models/banners.fields.video'), "video")
                ->sortable()
                ->searchable(),
            BooleanColumn::make(__('models/banners.fields.is_default'), "is_default")
                ->sortable()
                ->searchable(),
            Column::make("Actions", 'id')
                ->format(
                    fn($value, $row, Column $column) => view('bazintemplate::common.livewire-tables.actions', [
                        'showUrl' => route('cms.banners.show', $row->id),
                        'editUrl' => route('cms.banners.edit', $row->id),
                        'recordId' => $row->id,
                    ])
                )
        ];
    }
}

app/Http/Controllers/BannerController.php
<?php

namespace Modules\YindulaCms\app\Http\Controllers;

use Laracasts\Flash\Flash;
use Modules\YindulaCms\app\Http\Controllers\CmsBaseController;
use Modules\YindulaCms\app\Http\Requests\CreateBannerRequest;
use Modules\YindulaCms\app\Http\Requests\UpdateBannerRequest;
use Modules\YindulaCms\app\Repositories\BannerRepository;
use Modules\YindulaCms\app\Utilities\ContentTypes\CmsImage as Image;
use Modules\YindulaCore\Utilities\FilepondManager;
use Response;

class BannerController extends CmsBaseController
{
    /** @var BannerRepository $bannerRepository*/
    private $bannerRepository;

    public function __construct(BannerRepository $bannerRepo)
    {
        $this->bannerRepository = $bannerRepo;
    }

    /**
     * Display a listing of the Banner.
     *
     *
     * @return Response
     */
    public function index()
    {
        return view('yindulacms::banners.index');
    }

    /**
     * Show the form for creating a new Banner.
     *
     * @return Response
     */
    public function create()
    {
        return view('yindulacms::banners.create');
    }

    /**
     * Store a newly created Banner in storage.
     *
     * @param CreateBannerRequest $request
     *
     * @return Response
     */
    public function store(CreateBannerRequest $request)
    {
        $input = $request->all();

        $stored_file = new FilepondManager($request->image);

        $input['image'] = (new Image(
            $stored_file->getStoredFile(),
            $this->bannerRepository->modelName()
        ))->handle();

        $banner = $this->bannerRepository->create($input);

        Flash::success('Banner saved successfully.');

        return redirect(route('cms.banners.index'));
    }

    /**
     * Display the specified Banner.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $banner = $this->bannerRepository->find($id);

        if (empty($banner)) {
            Flash::error('Banner not found');

            return redirect(route('cms.banners.index'));
        }

        return view('yindulacms::banners.show')->with('banner', $banner);
    }

    /**
     * Show the form for editing the specified Banner.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $banner = $this->bannerRepository->find($id);

        if (empty($banner)) {
            Flash::error('Banner not found');

            return redirect(route('cms.banners.index'));
        }

        return view('yindulacms::banners.edit')->with('banner', $banner);
    }

    /**
     * Update the specified Banner in storage.
     *
     * @param int $id
     * @param UpdateBannerRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateBannerRequest $request)
    {
        $banner = $this->bannerRepository->find($id);

        if (empty($banner)) {
            Flash::error('Banner not found');

            return redirect(route('cms.banners.index'));
        }

        $input = $request->all();

        if ($request->image) {
            $stored_file = new FilepondManager($request->image);

            $input['image'] = (new Image(
                $stored_file->getStoredFile(),
                $this->bannerRepository->modelName()
            ))->handle();
        } else {
            $input['image'] = $banner->image;
        }


        $banner = $this->bannerRepository->update($input, $id);

        Flash::success('Banner updated successfully.');

        return redirect(route('cms.banners.index'));
    }

    /**
     * Remove the specified Banner from storage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $banner = $this->bannerRepository->find($id);

        if (empty($banner)) {
            Flash::error('Banner not found');

            return redirect(route('cms.banners.index'));
        }

        $this->bannerRepository->delete($id);

        Flash::success('Banner deleted successfully.');

        return redirect(route('cms.banners.index'));
    }
}

resources/views/banners/_filepond_image.blade.php
@section('css')
    <link href="https://unpkg.com/filepond@^4/dist/filepond.css" rel="stylesheet" />
@endsection

@push('scripts')
    <script src="https://unpkg.com/filepond@4.9.5/dist/filepond.js"></script>
    <script>
        // Set default FilePond options
        FilePond.setOptions({
            server: {
                url: "{{ config('filepond.server.url') }}",
                headers: {
                    'X-CSRF-TOKEN': "{{ @csrf_token() }}",
                }
            }
        });

        // Create the FilePond instance
        FilePond.create(document.querySelector('input[name="image"]'));
        FilePond.create(document.querySelector('input[name="image_two"]'));
        // FilePond.create(document.querySelector('input[name="filename[]"]'));
    </script>
@endpush

resources/views/banners/create.blade.php
@extends('bazintemplate::layouts.authed')

@section('title')
    Create Banner
@endsection

@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">New Banner</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('cms.banners.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div class="content">

            @include('bazintemplate::common.errors')

            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body ">
                                {!! Form::open(['route' => 'cms.banners.store', 'files' => true]) !!}
                                <div class="row">
                                    @include('yindulacms::banners.fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </section>
@endsection

resources/views/banners/edit.blade.php
@extends('bazintemplate::layouts.authed')
@section('title')
    Edit Banner
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">Edit Banner</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('cms.banners.index') }}"  class="btn btn-primary">Back</a>
                </div>
            </div>
  <div class="content">
              @include('bazintemplate::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($banner, ['route' => ['cms.banners.update', $banner->id], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('yindulacms::banners.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/banners/fields.blade.php
<!-- Title Field -->
<div class="form-group col-sm-6">
    {!! Form::label('title', 'Title:') !!}
    {!! Form::text('title', null, ['class' => 'form-control','maxlength' => 100,'maxlength' => 100]) !!}
</div>

<!-- Excerpt Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('excerpt', 'Excerpt:') !!}
    {!! Form::textarea('excerpt', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Image Field -->
<div class="form-group col-sm-6">
    {!! Form::label('image', 'Image:') !!}
    {!! Form::file('image', null, ['class' => 'form-control','maxlength' => 125,'maxlength' => 125]) !!}
</div>

<!-- Video Field -->
<div class="form-group col-sm-6">
    {!! Form::label('video', 'Video:') !!}
    {!! Form::file('video', null, ['class' => 'form-control','maxlength' => 125,'maxlength' => 125]) !!}
</div>

<!-- Is Default Field -->
<div class="form-group col-sm-6" style="padding-top: 37px">
    <div class="form-check">
        {!! Form::checkbox('is_default', '1', null, ['id' => 'is_default']) !!}
        <label class="form-check-label" for="is_default">
           is_default
        </label>
    </div>
</div>

<!-- Image Two Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('image_two', 'Image Two:') !!}
    {!! Form::file('image_two', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('cms.banners.index') }}" class="btn btn-light">Cancel</a>
</div>


@include('yindulacms::banners._filepond_image')

resources/views/banners/index.blade.php
@extends('bazintemplate::layouts.authed')

@section('title')
    @lang('models/banners.plural')
@endsection

@section('content')
    <section class="section">
        <div class="section-header">

            <h1>
                @lang('models/banners.plural')
            </h1>

            <div class="section-header-breadcrumb">
                <a href="{{ route('cms.banners.create') }}" class="btn btn-primary form-btn">
                    @lang('models/banners.singular')
                    <i class="fas fa-plus"></i>
                </a>
            </div>
        </div>
        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    <livewire:yindulacms::banners-table />
                </div>
            </div>
        </div>

    </section>
@endsection

resources/views/banners/show.blade.php
@extends('bazintemplate::layouts.authed')
@section('title')
    Banner Details
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>Banner Details</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('cms.banners.index') }}"
                 class="btn btn-primary form-btn float-right">Back</a>
        </div>
      </div>
   @include('bazintemplate::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('yindulacms::banners.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/banners/show_fields.blade.php
<!-- Title Field -->
<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    <p>{{ $banner->title }}</p>
</div>

<!-- Excerpt Field -->
<div class="form-group">
    {!! Form::label('excerpt', 'Excerpt:') !!}
    <p>{{ $banner->excerpt }}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $banner->description }}</p>
</div>

<!-- Image Field -->
<div class="form-group">
    {!! Form::label('image', 'Image:') !!}
    <p>{{ $banner->image }}</p>
</div>

<!-- Video Field -->
<div class="form-group">
    {!! Form::label('video', 'Video:') !!}
    <p>{{ $banner->video }}</p>
</div>

<!-- Is Default Field -->
<div class="form-group">
    {!! Form::label('is_default', 'Is Default:') !!}
    <p>{{ $banner->is_default }}</p>
</div>

<!-- Image Two Field -->
<div class="form-group">
    {!! Form::label('image_two', 'Image Two:') !!}
    <p>{{ $banner->image_two }}</p>
</div>