routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\YindulaCms\app\Http\Controllers\CmsEventController;
use Modules\YindulaCms\app\Http\Controllers\FeatureController;
use Modules\YindulaCms\app\Http\Controllers\PageSettingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('cms')->name('cms.')->group(function () {

    Route::middleware('auth')->group(function () {

        Route::get('/dashboard', 'YindulaCmsController@dashboard')->name('dashboard');

        Route::resource('banners', BannerController::class);
        Route::resource('categories', CategoryController::class);
        Route::resource('cmsSettings', CmsSettingController::class);

        Route::resource('posts', PostController::class);
        Route::resource('sliders', SliderController::class);
        Route::resource('cmsEvents', CmsEventController::class);

        Route::resource('galleries', GalleryController::class);
        Route::resource('menus', MenuController::class);

        /*
        |--------------------------------------------------------------------------
        | Pages
        |--------------------------------------------------------------------------|
        */
        Route::resource('pages', PageController::class);

        Route::post(
            'pages/setHomePage/{id}',
            [Modules\YindulaCms\app\Http\Controllers\PageController::class, 'setHomePage']
        )->name('pages.setHomePage');

        Route::post(
            'pages/setContactPage/{id}',
            [Modules\YindulaCms\app\Http\Controllers\PageController::class, 'setContactPage']
        )->name('pages.setContactPage');

        /*
        |--------------------------------------------------------------------------
        | Feature Sections
        |--------------------------------------------------------------------------|
        */
        Route::resource('featureSections', FeatureSectionController::class);

        Route::get('featureSectionsAdd/{pageId}', [
            FeatureSectionController::class, 'add'
        ])->name('featureSections.add');

        /*
        |--------------------------------------------------------------------------
        | Features
        |--------------------------------------------------------------------------|
        */
        Route::resource('features', FeatureController::class);
        Route::get('featuresAdd/{pageId}', [FeatureController::class, 'add'])->name('features.add');

        /*
        |--------------------------------------------------------------------------
        | Page Settings
        |--------------------------------------------------------------------------|
        */
        Route::resource('pageSettings', PageSettingController::class);

        Route::get('pageSettingsAdd/{pageId}', [
            PageSettingController::class, 'add'
        ])->name('pageSettings.add');

        Route::get('pageSettingsCreateOrEdit/{pageId}', [
            PageSettingController::class, 'createOrEdit'
        ])->name('pageSettings.createOrEdit');

        /*
        |==========================================================================|
        */
    });
});

app/Models/Category.php
<?php

namespace Modules\YindulaCms\app\Models;

use Cviebrock\EloquentSluggable\Sluggable;

use Eloquent as Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Modules\YindulaCms\app\Traits\UsesCmsDatabaseConnection;

/**
 * Class Category
 * @package Modules\YindulaCms\app\Models
 * @version February 24, 2022, 8:23 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection $featureSections
 * @property \Illuminate\Database\Eloquent\Collection $features
 * @property integer $parent_id
 * @property integer $order
 * @property string $name
 * @property string $slug
 */
class Category extends Model
{

    use HasFactory, Sluggable, UsesCmsDatabaseConnection;

    public $table = 'categories';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';




    public $fillable = [
        'parent_id',
        'order',
        'name',
        'slug'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'parent_id' => 'integer',
        'order' => 'integer',
        'name' => 'string',
        'slug' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'parent_id' => 'nullable|integer',
        'order' => 'required|integer',
        'name' => 'required|string|max:255',
        'slug' => 'required|string|max:255',
        'created_at' => 'nullable',
        'updated_at' => 'nullable'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function featureSections()
    {
        return $this->hasMany(\Modules\YindulaCms\app\Models\FeatureSection::class, 'category_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function features()
    {
        return $this->hasMany(\Modules\YindulaCms\app\Models\Feature::class, 'category_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function parentId()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function children()
    {
        return $this->hasMany(self::class, 'parent_id')
            ->with('children')->orderBy('order');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function posts()
    {
        return $this->hasMany(\Modules\YindulaCms\app\Models\Post::class)
            ->published()
            ->orderBy('created_at', 'DESC');
    }

    /*
    |---------------------------------------------------------------------------------------------
    | Custom Attributes
    |---------------------------------------------------------------------------------------------
    */
    /**
     * This attribute converts the "created_at" field into a more readable attribute.
     * It does not have a corresponding column in the database. It can be accessed
     * using the "snake case", e.g. $game_participant->readable_created_at.
     * @return void
     */
    public function getNameWithParentAttribute()
    {
        return $this->attributes['name'] . ' (' . $this->parentId->name . ')';
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name',
                'onUpdate'  => true,
                'separator' => '-',
            ]
        ];
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace Modules\YindulaCms\app\Http\Controllers;

use Flash;
use Modules\YindulaCms\app\DataTables\CategoryDataTable;
use Modules\YindulaCms\app\Http\Requests\CreateCategoryRequest;
use Modules\YindulaCms\app\Http\Requests\UpdateCategoryRequest;
use Modules\YindulaCms\app\Repositories\CategoryRepository;
use Modules\YindulaCms\app\Http\Controllers\CmsBaseController;
use Response;

class CategoryController extends CmsBaseController
{
    /** @var CategoryRepository $categoryRepository*/
    private $categoryRepository;

    public function __construct(CategoryRepository $categoryRepo)
    {
        $this->categoryRepository = $categoryRepo;
    }

    /**
     * Display a listing of the Category.
     *
     * @param CategoryDataTable $categoryDataTable
     *
     * @return Response
     */
    public function index(CategoryDataTable $categoryDataTable)
    {
        return $categoryDataTable->render('yindulacms::categories.index');
    }

    /**
     * Show the form for creating a new Category.
     *
     * @return Response
     */
    public function create()
    {
        return view('yindulacms::categories.create');
    }

    /**
     * Store a newly created Category in storage.
     *
     * @param CreateCategoryRequest $request
     *
     * @return Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $input = $request->all();

        $category = $this->categoryRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/categories.singular')]));

        return redirect(route('cms.categories.index'));
    }

    /**
     * Display the specified Category.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('messages.not_found', ['model' => __('models/categories.singular')]));

            return redirect(route('cms.categories.index'));
        }

        return view('yindulacms::categories.show')->with('category', $category);
    }

    /**
     * Show the form for editing the specified Category.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('messages.not_found', ['model' => __('models/categories.singular')]));

            return redirect(route('cms.categories.index'));
        }

        return view('yindulacms::categories.edit')->with('category', $category);
    }

    /**
     * Update the specified Category in storage.
     *
     * @param int $id
     * @param UpdateCategoryRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCategoryRequest $request)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('messages.not_found', ['model' => __('models/categories.singular')]));

            return redirect(route('cms.categories.index'));
        }

        $category = $this->categoryRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/categories.singular')]));

        return redirect(route('cms.categories.index'));
    }

    /**
     * Remove the specified Category from storage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error(__('messages.not_found', ['model' => __('models/categories.singular')]));

            return redirect(route('cms.categories.index'));
        }

        $this->categoryRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/categories.singular')]));

        return redirect(route('cms.categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('bazintemplate::layouts.authed')
@section('title')
    @lang('crud.add_new') @lang('models/categories.singular')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">@lang('crud.add_new') @lang('models/categories.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('cms.categories.index') }}" class="btn btn-primary">@lang('crud.back')</a>
            </div>
        </div>
        <div class="content">
            @include('bazintemplate::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'cms.categories.store']) !!}
                                    <div class="row">
                                        @include('yindulacms::categories.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/categories/datatables_actions.blade.php
{!! Form::open(['route' => ['cms.categories.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('cms.categories.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('cms.categories.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => 'return confirm("'.__('crud.are_you_sure').'")'
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/categories/edit.blade.php
@extends('bazintemplate::layouts.authed')
@section('title')
    @lang('crud.edit') @lang('models/categories.singular')
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">@lang('crud.edit') @lang('models/categories.singular')</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('cms.categories.index') }}"  class="btn btn-primary">@lang('crud.back')</a>
                </div>
            </div>
  <div class="content">
              @include('bazintemplate::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($category, ['route' => ['categories.update', $category->id], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('yindulacms::categories.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/categories/fields.blade.php
<!-- Parent Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('parent_id', __('models/categories.fields.parent_id').':') !!}
    {!! Form::number('parent_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Order Field -->
<div class="form-group col-sm-6">
    {!! Form::label('order', __('models/categories.fields.order').':') !!}
    {!! Form::number('order', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', __('models/categories.fields.name').':') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Slug Field -->
<div class="form-group col-sm-6">
    {!! Form::label('slug', __('models/categories.fields.slug').':') !!}
    {!! Form::text('slug', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('cms.categories.index') }}" class="btn btn-light">@lang('crud.cancel')</a>
</div>

resources/views/categories/index.blade.php
@extends('bazintemplate::layouts.authed')
@section('title')
     @lang('models/categories.plural')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>@lang('models/categories.plural')</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('cms.categories.create')}}" class="btn btn-primary form-btn">@lang('crud.add_new')<i class="fas fa-plus"></i></a>
            </div>
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('yindulacms::categories.table')
            </div>
       </div>
   </div>

    </section>
@endsection

resources/views/categories/show.blade.php
@extends('bazintemplate::layouts.authed')

@section('title')
    @lang('models/categories.singular') @lang('crud.details')
@endsection

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>@lang('models/categories.singular') @lang('crud.details')</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('cms.categories.index') }}"
                    class="btn btn-primary form-btn float-right">@lang('crud.back')</a>
            </div>
        </div>
        @include('bazintemplate::common.errors')
        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    @include('yindulacms::categories.show_fields')
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/categories/show_fields.blade.php
<!-- Parent Id Field -->
<div class="form-group">
    {!! Form::label('parent_id', __('models/categories.fields.parent_id').':') !!}
    <p>{{ $category->parent_id }}</p>
</div>

<!-- Order Field -->
<div class="form-group">
    {!! Form::label('order', __('models/categories.fields.order').':') !!}
    <p>{{ $category->order }}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', __('models/categories.fields.name').':') !!}
    <p>{{ $category->name }}</p>
</div>

<!-- Slug Field -->
<div class="form-group">
    {!! Form::label('slug', __('models/categories.fields.slug').':') !!}
    <p>{{ $category->slug }}</p>
</div>

resources/views/categories/table.blade.php
@section('css')
    @include('yindulacms::layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('yindulacms::layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush