routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\YindulaCms\app\Http\Controllers\CmsEventController;
use Modules\YindulaCms\app\Http\Controllers\FeatureController;
use Modules\YindulaCms\app\Http\Controllers\PageSettingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('cms')->name('cms.')->group(function () {

    Route::middleware('auth')->group(function () {

        Route::get('/dashboard', 'YindulaCmsController@dashboard')->name('dashboard');

        Route::resource('banners', BannerController::class);
        Route::resource('categories', CategoryController::class);
        Route::resource('cmsSettings', CmsSettingController::class);

        Route::resource('posts', PostController::class);
        Route::resource('sliders', SliderController::class);
        Route::resource('cmsEvents', CmsEventController::class);

        Route::resource('galleries', GalleryController::class);
        Route::resource('menus', MenuController::class);

        /*
        |--------------------------------------------------------------------------
        | Pages
        |--------------------------------------------------------------------------|
        */
        Route::resource('pages', PageController::class);

        Route::post(
            'pages/setHomePage/{id}',
            [Modules\YindulaCms\app\Http\Controllers\PageController::class, 'setHomePage']
        )->name('pages.setHomePage');

        Route::post(
            'pages/setContactPage/{id}',
            [Modules\YindulaCms\app\Http\Controllers\PageController::class, 'setContactPage']
        )->name('pages.setContactPage');

        /*
        |--------------------------------------------------------------------------
        | Feature Sections
        |--------------------------------------------------------------------------|
        */
        Route::resource('featureSections', FeatureSectionController::class);

        Route::get('featureSectionsAdd/{pageId}', [
            FeatureSectionController::class, 'add'
        ])->name('featureSections.add');

        /*
        |--------------------------------------------------------------------------
        | Features
        |--------------------------------------------------------------------------|
        */
        Route::resource('features', FeatureController::class);
        Route::get('featuresAdd/{pageId}', [FeatureController::class, 'add'])->name('features.add');

        /*
        |--------------------------------------------------------------------------
        | Page Settings
        |--------------------------------------------------------------------------|
        */
        Route::resource('pageSettings', PageSettingController::class);

        Route::get('pageSettingsAdd/{pageId}', [
            PageSettingController::class, 'add'
        ])->name('pageSettings.add');

        Route::get('pageSettingsCreateOrEdit/{pageId}', [
            PageSettingController::class, 'createOrEdit'
        ])->name('pageSettings.createOrEdit');

        /*
        |==========================================================================|
        */
    });
});

Livewire/FeatureSections/CreateOrUpdateForm.php
<?php

namespace Modules\YindulaCms\Livewire\FeatureSections;

use Illuminate\Contracts\View\View;
use Livewire\Attributes\Locked;
use Livewire\Attributes\On;
use Livewire\Attributes\Rule;
use Livewire\Component;
use Modules\YindulaCms\app\Models\FeatureSection;

class CreateOrUpdateForm extends Component
{

    public $pageId;

    #[Locked]
    public int $featureSectionId;

    public ?FeatureSection $model;


    // #[Rule('required')]
    // public string $name = '';
    // #[Rule('required|numeric')]
    // public string $price = '';

    public function mount($pageId = null): void
    {
        $this->pageId = $pageId;
    }

    public function edit(int $featureSectionId): void
    {
        $this->model = FeatureSection::where('id', $featureSectionId)->first();
        $this->featureSectionId = $featureSectionId;

        // $this->name = $this->model->name;
        // $this->price = $this->model->price;
    }

    public function save(): void
    {
        $this->validate();

        if (empty($this->model)) {
            FeatureSection::create([
                'name' => $this->name,
                'price' => $this->price,
            ]);
        } else {
            $this->model->update([
                'name' => $this->name,
                'price' => $this->price,
            ]);
        }

        $this->reset('model', 'name', 'price', 'showModal');
    }

    public function render(): View
    {
        return view('yindulacms::livewire.feature_sections.feature-section-create');
    }
}

Livewire/FeatureSections/FeatureSectionsTable.php
<?php

namespace Modules\YindulaCms\Livewire\FeatureSections;

use Laracasts\Flash\Flash;
use Modules\YindulaCms\app\Models\Page;
use Illuminate\Database\Eloquent\Builder;
use Modules\YindulaCms\app\Models\FeatureSection;
use Rappasoft\LaravelLivewireTables\Views\Column;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Columns\BooleanColumn;
use Modules\YindulaCms\app\Repositories\FeatureSectionRepository;

class FeatureSectionsTable extends DataTableComponent
{
    protected $model = FeatureSection::class;

    protected $listeners = ['deleteRecord' => 'deleteRecord'];

    public $pageId;


    public function mount(Page $page = null)
    {
        // if $page is not null,
        // it will set $this->pageId to the value of $page->id
        // otherwise, it will set it to null.
        $this->pageId = $page ? $page->id : null;
    }

    public function builder(): Builder
    {
        $builder = FeatureSection::query();

        if (!is_null($this->pageId)) {
            $builder->where('page_id', $this->pageId);
        }

        return $builder;
    }

    public function deleteRecord($id)
    {
        app(FeatureSectionRepository::class)->delete($id);
        Flash::success(__('messages.deleted', ['model' => __('models/featureSections.singular')]));

        $this->dispatch('refreshDatatable');
    }

    public function configure(): void
    {
        $this->setPrimaryKey('id');
            // ->setReorderEnabled();
    }

    public function bulkActions(): array
    {
        return [
            'activate' => 'Activate',
            'deactivate' => 'Deactivate',
        ];
    }

    // public function activate()
    // {
    //     $this->model::whereIn('id', $this->getSelected())->update(['is_active' => true]);

    //     $this->clearSelected();
    // }

    // public function deactivate()
    // {
    //     $this->model::whereIn('id', $this->getSelected())->update(['is_active' => false]);

    //     $this->clearSelected();
    // }

    public function columns(): array
    {
        return [
            // Column::make("Category Id", "category_id")
            //     ->sortable()
            //     ->searchable(),
            Column::make(__('models/featureSections.fields.name'), "name")
                ->sortable()
                ->searchable(),
            Column::make(__('models/featureSections.fields.key'), "key")
                ->sortable()
                ->searchable(),
            Column::make(__('models/featureSections.fields.title'), "title")
                ->sortable()
                ->searchable(),
            // Column::make("Image", "image")
            //     ->sortable()
            //     ->searchable(),
            // Column::make("Description", "description")
            //     ->sortable()
            //     ->searchable(),
            BooleanColumn::make(__('models/featureSections.fields.is_active'), "is_active")
                ->sortable()
                ->searchable(),
            Column::make(__('models/featureSections.fields.page_id'), "page.title")
                ->sortable()
                ->searchable(),
            Column::make("Actions", 'id')
                ->format(
                    fn ($value, $row, Column $column) => view('bazintemplate::common.livewire-tables.actions', [
                        'showUrl' => route('cms.featureSections.show', $row->id),
                        'editUrl' => route('cms.featureSections.edit', $row->id),
                        'recordId' => $row->id,
                    ])
                )
        ];
    }
}

app/Http/Controllers/FeatureSectionController.php
<?php

namespace Modules\YindulaCms\app\Http\Controllers;


use Response;
use Laracasts\Flash\Flash;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Request;
use Modules\YindulaCore\Utilities\FilepondManager;
use Modules\YindulaCms\app\Repositories\PageRepository;
use Modules\YindulaCms\app\Http\Controllers\CmsBaseController;
use Modules\YindulaCms\app\Repositories\FeatureSectionRepository;
use Modules\YindulaCms\app\Utilities\ContentTypes\CmsImage as Image;
use Modules\YindulaCms\app\Http\Requests\CreateFeatureSectionRequest;
use Modules\YindulaCms\app\Http\Requests\UpdateFeatureSectionRequest;

class FeatureSectionController extends CmsBaseController
{
    /** @var  FeatureSectionRepository */
    private $featureSectionRepository;

    /** @var  PageRepository */
    private $pageRepository;

    public function __construct(FeatureSectionRepository $featureSectionRepo, PageRepository $pageRepo)
    {
        $this->featureSectionRepository = $featureSectionRepo;
        $this->pageRepository = $pageRepo;
    }

    /**
     * Redirect based on the presence of page ID in the current URL.
     *
     * @return Redirector
     */
    private function redirectToPageOrIndex($pageId = null)
    {
        /* // Check if there is a page ID in the current URL
        $currentPageId = Request::route('pageId');

        // if (Route::currentRouteName() == 'cms.featureSections.add') {
        if ($currentPageId) { */

            // Redirect to the current page ID
            return redirect()->route('cms.pages.show', ['page' => $pageId]);
            
        // } else {
        //     // Redirect to cms.featureSections.index if no page ID is present
        //     return redirect()->route('cms.featureSections.index');
        // }
    }

    /**
     * Display a listing of the FeatureSection.
     *
     * @return Response
     */
    public function index()
    {
        return view('yindulacms::feature_sections.index');
    }

    /**
     * Show the form for creating a new FeatureSection.
     *
     * @return Response
     */
    public function create()
    {
        return view('yindulacms::feature_sections.create');
    }

    /**
     * Show the form for creating a new FeatureSection.
     *
     * @return Response
     */
    public function add($pageId)
    {
        $page = $this->pageRepository->find($pageId);
        return view('yindulacms::feature_sections.create')->with('page', $page);
    }

    /**
     * Store a newly created FeatureSection in storage.
     *
     * @param CreateFeatureSectionRequest $request
     *
     * @return Response
     */
    public function store(CreateFeatureSectionRequest $request)
    {
        $input = $request->all();

        $stored_file = new FilepondManager($request->image);

        $input['image'] = (new Image(
            $stored_file->getStoredFile(),
            $this->featureSectionRepository->modelName()
        ))->handle();

        $featureSection = $this->featureSectionRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/featureSections.singular')]));

        // Use the method to redirect based on the page ID
        return $this->redirectToPageOrIndex($input['page_id']);
    }

    /**
     * Display the specified FeatureSection.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $featureSection = $this->featureSectionRepository->find($id);

        if (empty($featureSection)) {
            Flash::error(__('messages.not_found', ['model' => __('models/featureSections.singular')]));

            return redirect(route('cms.featureSections.index'));
        }

        return view('yindulacms::feature_sections.show')->with('featureSection', $featureSection);
    }

    /**
     * Show the form for editing the specified FeatureSection.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $featureSection = $this->featureSectionRepository->find($id);

        if (empty($featureSection)) {
            Flash::error(__('messages.not_found', ['model' => __('models/featureSections.singular')]));

            return redirect(route('cms.featureSections.index'));
        }

        return view('yindulacms::feature_sections.edit')->with('featureSection', $featureSection);
    }

    /**
     * Update the specified FeatureSection in storage.
     *
     * @param  int              $id
     * @param UpdateFeatureSectionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateFeatureSectionRequest $request)
    {
        $featureSection = $this->featureSectionRepository->find($id);

        if (empty($featureSection)) {
            Flash::error(__('messages.not_found', ['model' => __('models/featureSections.singular')]));

            return redirect(route('cms.featureSections.index'));
        }


        $input = $request->all();


        if (isset($request->image)) {
            $stored_file = new FilepondManager($request->image);

            $input['image'] = (new Image(
                $stored_file->getStoredFile(),
                $this->featureSectionRepository->modelName()
            ))->handle();
        } else {
            $input['image'] = $featureSection->image;
        }

        $featureSection = $this->featureSectionRepository->update($input, $id);

        Flash::success(__('messages.updated', ['model' => __('models/featureSections.singular')]));

        return redirect(route('cms.featureSections.index'));
    }

    /**
     * Remove the specified FeatureSection from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $featureSection = $this->featureSectionRepository->find($id);

        if (empty($featureSection)) {
            Flash::error(__('messages.not_found', ['model' => __('models/featureSections.singular')]));

            return redirect(route('cms.featureSections.index'));
        }

        $this->featureSectionRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/featureSections.singular')]));

        return redirect(route('cms.featureSections.index'));
    }
}

resources/views/feature_sections/_fields.blade.php
<div class="form-group col-sm-6">
    
    @if (isset($page))
        <!-- Hidden Page Id Field -->
        <div class="form-group col-sm-12">
            {!! Form::hidden('page_id', $page->id) !!}
        </div>
    @else
        <!-- Page Id Field -->
        <div class="form-group col-sm-12">
            {!! Form::label('page_id', __('yindulacms::models/featureSections.fields.page_id') . ':') !!}
            {!! Form::select('page_id', $pageItems, null, ['class' => ['form-control', 'select2']]) !!}
        </div>
    @endif

    <!-- Category Id Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('category_id', __('yindulacms::models/featureSections.fields.category_id') . ':') !!}
        {!! Form::select('category_id', $categoryItems, null, ['class' => ['form-control', 'select2']]) !!}
    </div>

    <!-- Description Field style="display: none" -->
    <div class="form-group col-sm-12 col-lg-12">
        {!! Form::label('description', __('yindulacms::models/featureSections.fields.description') . ':') !!}
        {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
    </div>

</div>

<div class="form-group col-sm-6">

    <!-- Is Active Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('is_active', __('yindulacms::models/featureSections.fields.is_active') . ':') !!}
        <label class="checkbox-inline">
            {!! Form::hidden('is_active', 0) !!}
            {!! Form::checkbox('is_active', '1', null) !!}
        </label>
    </div>

    <!-- Name Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('name', __('yindulacms::models/featureSections.fields.name') . ':') !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Title Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('title', __('yindulacms::models/featureSections.fields.title') . ':') !!}
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Image Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('image', __('yindulacms::models/pages.fields.image') . ':') !!}
        {!! Form::file('image') !!}
    </div>

</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('cms.featureSections.index') }}" class="btn btn-light">@lang('crud.cancel')</a>
</div>


@include('yindulacms::common.filepond_image')

resources/views/feature_sections/_filepond.blade.php
@section('css')
    <link href="https://unpkg.com/filepond@^4/dist/filepond.css" rel="stylesheet" />
@endsection

@push('scripts')
    <script src="https://unpkg.com/filepond@^4/dist/filepond.js"></script>
    <script>
        // Set default FilePond options
        FilePond.setOptions({
            server: {
                process: "{{ config('filepond.server.process') }}",
                revert: "{{ config('filepond.server.revert') }}",
                headers: {
                    'X-CSRF-TOKEN': "{{ @csrf_token() }}",
                }
            }
        });

        // Create the FilePond instance
        FilePond.create(document.querySelector('input[name="image"]'));
        // FilePond.create(document.querySelector('input[name="filename[]"]'));
    </script>
@endpush

resources/views/feature_sections/_show_fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', __('models/featureSections.fields.name').':') !!}
    <p>{{ $featureSection->name }}</p>
</div>

<!-- Title Field -->
<div class="form-group col-sm-6">
    {!! Form::label('title', __('models/featureSections.fields.title').':') !!}
    <p>{{ $featureSection->title }}</p>
</div>

<!-- Key Field -->
<div class="form-group col-sm-6">
    {!! Form::label('key', __('models/featureSections.fields.key').':') !!}
    <p>{{ $featureSection->key }}</p>
</div>


<!-- Page Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('page_id', __('models/featureSections.fields.page_id').':') !!}
    <p>{{ $featureSection->page_id }}</p>
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', __('models/featureSections.fields.description').':') !!}
    <p>{{ $featureSection->description }}</p>
</div>

<!-- Is Active Field -->
<div class="form-group col-sm-6">
    {!! Form::label('is_active', __('models/featureSections.fields.is_active').':') !!}
    <p>{{ $featureSection->is_active }}</p>
</div>

resources/views/feature_sections/_show_horizontal_nav_pills.blade.php
 <div class="row">
     <div class="col-12 col-sm-12 col-lg-12">
         <div class="card">
             <div class="card-header">

                 <div class="section-header-breadcrumb">
                    <a href="{{ route('cms.featureSections.add', ['pageId' => $page->id]) }}" class="btn btn-primary form-btn">
                        @lang('crud.add_new') Section
                        <i class="fas fa-plus"></i>
                    </a>
                </div>
{{--
                <div class="section-header-breadcrumb">
                    <a href="{{ route('cms.features.create') }}" class="btn btn-primary form-btn">
                        @lang('crud.add_new') Feature
                        <i class="fas fa-plus"></i>
                    </a>
                </div> --}}

             </div>
             <div class="card-body">
                 <ul class="nav nav-pills" id="myTab3" role="tablist">
                     <li class="nav-item">
                         <a class="nav-link active show" id="sections-tab3" data-toggle="tab" href="#sections3"
                             role="tab" aria-controls="sections" aria-selected="true">
                             Section List
                         </a>
                     </li>
                     {{-- <li class="nav-item">
                         <a class="nav-link" id="features-tab3" data-toggle="tab" href="#features3" role="tab"
                             aria-controls="features" aria-selected="false">
                             Create Form
                         </a>
                     </li> --}}
                 </ul>
                 <div class="tab-content" id="myTabContent2">
                     <div class="tab-pane fade active show" id="sections3" role="tabpanel"
                         aria-labelledby="sections-tab3">
                         <div class="row">
                             <livewire:yindulacms::feature-sections.feature-sections-table :page="$page"
                                 :key="time() . $page->id" />
                         </div>
                     </div>
                     <div class="tab-pane fade" id="features3" role="tabpanel" aria-labelledby="features-tab3">
                         <livewire:yindulacms::feature-sections.create-or-update-form :page="$page"
                             :key="time() . $page->id" />
                     </div>
                 </div>
             </div>
         </div>
     </div>
 </div>

resources/views/feature_sections/create.blade.php
@extends('bazintemplate::layouts.authed')

@section('title')
    @lang('crud.add_new') @lang('models/featureSections.singular')
@endsection

@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">@lang('crud.add_new') @lang('models/featureSections.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('cms.featureSections.index') }}" class="btn btn-primary">@lang('crud.back')</a>
            </div>
        </div>
        <div class="content">
            @include('bazintemplate::common.errors')
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body ">
                                {!! Form::open(['route' => 'cms.featureSections.store']) !!}
                                <div class="row">
                                    @include('yindulacms::feature_sections._fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/feature_sections/edit.blade.php
@extends('bazintemplate::layouts.authed')

@section('title')
    @lang('crud.edit') @lang('models/featureSections.singular')
@endsection

@section('content')
    <section class="section">

        <div class="section-header">
            <h3 class="page__heading m-0">@lang('crud.edit') @lang('models/featureSections.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('cms.featureSections.index') }}" class="btn btn-primary">@lang('crud.back')</a>
            </div>
        </div>

        <div class="content">
            @include('bazintemplate::common.errors')
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body ">
                                {!! Form::model($featureSection, ['route' => ['cms.featureSections.update', $featureSection->id], 'method' => 'patch']) !!}
                                <div class="row">
                                    @include('yindulacms::feature_sections._fields')
                                </div>

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
@endsection

resources/views/feature_sections/index.blade.php
@extends('bazintemplate::layouts.authed')

@section('title')
    @lang('models/featureSections.plural')
@endsection

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>@lang('models/featureSections.plural')</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('cms.featureSections.create') }}" class="btn btn-primary form-btn">@lang('crud.add_new')
                    <i class="fas fa-plus"></i>
                </a>
            </div>
        </div>
        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    <livewire:yindulacms::feature-sections.feature-sections-table />
                </div>
            </div>
        </div>

    </section>
@endsection

resources/views/feature_sections/show.blade.php
@extends('bazintemplate::layouts.authed')

@section('title')
    @lang('models/featureSections.singular') @lang('crud.details')
@endsection

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>@lang('models/featureSections.singular') @lang('crud.details')</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('cms.featureSections.index') }}"
                    class="btn btn-primary form-btn float-right">@lang('crud.back')</a>
            </div>
        </div>

        @include('bazintemplate::common.errors')

        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        @include('yindulacms::feature_sections._show_fields')
                    </div>
                    @livewire('yindulacms::features-table', ['featureSection' => $featureSection])
                </div>
            </div>
        </div>
    </section>
@endsection