routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\YindulaCms\app\Http\Controllers\CmsEventController;
use Modules\YindulaCms\app\Http\Controllers\FeatureController;
use Modules\YindulaCms\app\Http\Controllers\PageSettingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('cms')->name('cms.')->group(function () {

    Route::middleware('auth')->group(function () {

        Route::get('/dashboard', 'YindulaCmsController@dashboard')->name('dashboard');

        Route::resource('banners', BannerController::class);
        Route::resource('categories', CategoryController::class);
        Route::resource('cmsSettings', CmsSettingController::class);

        Route::resource('posts', PostController::class);
        Route::resource('sliders', SliderController::class);
        Route::resource('cmsEvents', CmsEventController::class);

        Route::resource('galleries', GalleryController::class);
        Route::resource('menus', MenuController::class);

        /*
        |--------------------------------------------------------------------------
        | Pages
        |--------------------------------------------------------------------------|
        */
        Route::resource('pages', PageController::class);

        Route::post(
            'pages/setHomePage/{id}',
            [Modules\YindulaCms\app\Http\Controllers\PageController::class, 'setHomePage']
        )->name('pages.setHomePage');

        Route::post(
            'pages/setContactPage/{id}',
            [Modules\YindulaCms\app\Http\Controllers\PageController::class, 'setContactPage']
        )->name('pages.setContactPage');

        /*
        |--------------------------------------------------------------------------
        | Feature Sections
        |--------------------------------------------------------------------------|
        */
        Route::resource('featureSections', FeatureSectionController::class);

        Route::get('featureSectionsAdd/{pageId}', [
            FeatureSectionController::class, 'add'
        ])->name('featureSections.add');

        /*
        |--------------------------------------------------------------------------
        | Features
        |--------------------------------------------------------------------------|
        */
        Route::resource('features', FeatureController::class);
        Route::get('featuresAdd/{pageId}', [FeatureController::class, 'add'])->name('features.add');

        /*
        |--------------------------------------------------------------------------
        | Page Settings
        |--------------------------------------------------------------------------|
        */
        Route::resource('pageSettings', PageSettingController::class);

        Route::get('pageSettingsAdd/{pageId}', [
            PageSettingController::class, 'add'
        ])->name('pageSettings.add');

        Route::get('pageSettingsCreateOrEdit/{pageId}', [
            PageSettingController::class, 'createOrEdit'
        ])->name('pageSettings.createOrEdit');

        /*
        |==========================================================================|
        */
    });
});

app/Models/Page.php
<?php

namespace Modules\YindulaCms\app\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Eloquent as Model;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Str;
use Modules\YindulaCms\app\Enums\PageStatus;
use Modules\YindulaCms\app\Http\Observers\After\PageObserverAfter;
use Modules\YindulaCms\app\Http\Observers\Before\PageObserverBefore;
use Modules\YindulaCms\app\Utilities\PageHelper;
use Modules\YindulaCms\app\Traits\UsesCmsDatabaseConnection;

/**
 * Class Page
 *
 * @package Modules\Cms\Entities
 * @version January 3, 2022, 12:53 pm UTC
 * @property \Illuminate\Database\Eloquent\Collection $featureSections
 * @property \Illuminate\Database\Eloquent\Collection $features
 * @property integer $author_id
 * @property string $title
 * @property string $subtitle
 * @property string $excerpt
 * @property string $body
 * @property string $image
 * @property string $slug
 * @property string $meta_description
 * @property string $meta_keywords
 * @property string $status
 * @property boolean $is_home
 * @property boolean $is_page
 * @property int $id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\User|null $author
 * @property-read \Illuminate\Database\Eloquent\Collection|\Modules\YindulaCms\app\Models\FeatureSection[] $featureSection
 * @property-read int|null $feature_section_count
 * @property-read int|null $feature_sections_count
 * @property-read int|null $features_count
 * @property-read void $readable_is_home
 * @property-read void $readable_is_page
 * @property-read mixed $truncated_body
 * @method static \Illuminate\Database\Eloquent\Builder|Page active()
 * @method static \Illuminate\Database\Eloquent\Builder|Page allPages()
 * @method static \Illuminate\Database\Eloquent\Builder|Page findSimilarSlugs(string $attribute, array $config, string $slug)
 * @method static \Illuminate\Database\Eloquent\Builder|Page isAbout()
 * @method static \Illuminate\Database\Eloquent\Builder|Page isPage()
 * @method static \Illuminate\Database\Eloquent\Builder|Page newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Page newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Page query()
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereAuthorId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereBody($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereExcerpt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereIsHome($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereIsContact($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereIsPage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereMetaDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereMetaKeywords($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereSubtitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page withUniqueSlugConstraints(\Illuminate\Database\Eloquent\Model $model, string $attribute, array $config, string $slug)
 * @mixin Model
 */
class Page extends Model
{

    use HasFactory, Sluggable, UsesCmsDatabaseConnection;

    public $table = 'pages';


    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title',
                'onUpdate'  => true,
                'separator' => '-',
            ]
        ];
    }


    public $fillable = [
        'author_id',
        'title',
        'subtitle',
        'excerpt',
        'body',
        'image',
        'slug',
        'meta_description',
        'meta_keywords',
        'status',
        'is_home',
        'is_contact',
        'is_page',
        'is_event'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'author_id' => 'integer',
        'title' => 'string',
        'subtitle' => 'string',
        'excerpt' => 'string',
        'body' => 'string',
        'image' => 'string',
        'slug' => 'string',
        'meta_description' => 'string',
        'meta_keywords' => 'string',
        'status' => 'string',
        'is_home' => 'boolean',
        'is_contact' => 'boolean',
        'is_page' => 'boolean',
        'is_event' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'author_id' => 'integer|integer',
        'title' => 'required|string|max:255|string|max:255',
        'subtitle' => 'nullable|string|max:255',
        'excerpt' => 'string|nullable|string',
        'body' => 'string|nullable|string',
        'image' => 'string|max:255|nullable|string|max:255',
        'slug' => 'string|max:255|string|max:255',
        'meta_description' => 'nullable|string|nullable|string',
        'meta_keywords' => 'nullable|string|nullable|string',
        'status' => 'required|string|string',
        'is_home' => 'nullable|boolean',
        'is_contact' => 'nullable|boolean',
        'is_page' => 'nullable|boolean',
        'is_event' => 'nullable|boolean',
        'created_at' => 'nullable|nullable',
        'updated_at' => 'nullable|nullable'
    ];


    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        self::observe(PageObserverBefore::class);
        self::observe(PageObserverAfter::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     **/
    public function author()
    {
        return $this->belongsTo(\App\Models\User::class, 'author_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function featureSections()
    {
        return $this->hasMany(\Modules\YindulaCms\app\Models\FeatureSection::class, 'page_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function features()
    {
        return $this->hasMany(\Modules\YindulaCms\app\Models\Feature::class, 'page_id');
    }

    public function featureSection()
    {
        return $this->hasMany(FeatureSection::class);
    }


    /**
     * Scope a query to only include active pages.
     *
     * @param  $query  \Illuminate\Database\Eloquent\Builder
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('status', PageStatus::STATUS_ACTIVE);
    }


    public function getTruncatedBodyAttribute()
    {
        $body = Str::words($this->body, 30);
        return strip_tags($body);
    }

    public function getHomePageImage()
    {
        return self::where('is_home', 1)->pluck('image')->first();
    }


    public function scopeIsPage($query)
    {
        return $query->where('is_page', 1);
    }


    public function scopeIsAbout($query)
    {
        return $query->where('is_about', 1);
    }


    public function scopeAllPages($query)
    {
        return $query->where('is_page', 1)->where('is_page', 0);
    }

    /*
    |---------------------------------------------------------------------------------------------
    | Custom Attributes
    |---------------------------------------------------------------------------------------------
    */
    /**
     * This attribute converts the "created_at" field into a more readable attribute.
     * It does not have a corresponding column in the database. It can be accessed
     * using the "snake case", e.g. $game_participant->readable_created_at.
     * @return void
     */
    public function getReadableIsHomeAttribute()
    {
        return ($this->attributes['is_home']) ? "Yes" : "No";
    }

    /**
     * This attribute converts the "created_at" field into a more readable attribute. It tells
     * the time ago instead of the exact time and does not have a corresponding column in the
     * database. It can be accessed using the "snake case", e.g. $game_participant->time_ago_created_at.
     * @return void
     */
    public function getReadableIsPageAttribute()
    {
        return ($this->attributes['is_page']) ? "Yes" : "No";
    }

    /**
     *
     * @return string
     */
    public function getImageUrlAttribute(): string
    {
        return PageHelper::getImageAttribute($this->id);
    }
}

resources/views/pages/_fields.blade.php
<div class="form-group col-sm-6">

    <!-- Title Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('title', __('yindulacms::models/pages.fields.title') . ':') !!}
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
    </div>

    @if ($page_setting && $page_setting->has_subtitle)
        <!-- Subtitle Field -->
        <div class="form-group col-sm-12">
            {!! Form::label('subtitle', __('yindulacms::models/pages.fields.subtitle') . ':') !!}
            {!! Form::text('subtitle', null, ['class' => 'form-control']) !!}
        </div>
    @endif

    <!-- Is Home Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('is_home', __('yindulacms::models/pages.fields.is_home') . ':') !!}
        <label class="checkbox-inline">
            {!! Form::hidden('is_home', 0) !!}
            {!! Form::checkbox('is_home', '1', null, ['id' => 'is_home_checkbox']) !!}
        </label>
    </div>

    <!-- Is Page Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('is_page', __('yindulacms::models/pages.fields.is_page') . ':') !!}
        <label class="checkbox-inline">
            {!! Form::hidden('is_page', 0) !!}
            {!! Form::checkbox('is_page', '1', null, ['id' => 'is_page_checkbox']) !!}
        </label>
    </div>

    @if ($page_setting && $page_setting->has_excerpt)
        <!-- Excerpt Field -->
        <div class="form-group col-sm-12 col-lg-12">
            {!! Form::label('excerpt', __('yindulacms::models/pages.fields.excerpt') . ':') !!}
            {!! Form::textarea('excerpt', null, ['class' => 'form-control']) !!}
        </div>
    @endif

</div>

<div class="form-group col-sm-6">

    @if ($page_setting && $page_setting->has_image)
        <!-- Image Field -->
        <div class="form-group col-sm-12">
            {!! Form::label('image', __('yindulacms::models/pages.fields.image') . ':') !!}
            {!! Form::file('image') !!}
        </div>
    @endif

    <!-- Status Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('status', __('yindulacms::models/pages.fields.status') . ':') !!}
        {!! Form::select('status', $statuses, ['class' => 'form-control select2']) !!}
    </div>


    @if ($page_setting && $page_setting->has_meta_description)
        <!-- Meta Description Field -->
        <div class="form-group col-sm-12 col-lg-12">
            {!! Form::label('meta_description', __('yindulacms::models/pages.fields.meta_description') . ':') !!}
            {!! Form::textarea('meta_description', null, ['class' => 'form-control']) !!}
        </div>
    @endif

    @if ($page_setting && $page_setting->has_meta_keywords)
        <!-- Meta Keywords Field -->
        <div class="form-group col-sm-12 col-lg-12">
            {!! Form::label('meta_keywords', __('yindulacms::models/pages.fields.meta_keywords') . ':') !!}
            {!! Form::textarea('meta_keywords', null, ['class' => 'form-control']) !!}
        </div>
    @endif

</div>

@if ($page_setting && $page_setting->has_body)
    <!-- Body Field -->
    <div class="form-group col-sm-12 col-lg-12">
        {!! Form::label('body', __('yindulacms::models/pages.fields.body') . ':') !!}
        {!! Form::textarea('body', null, ['class' => 'form-control']) !!}
    </div>
@endif

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('cms.pages.index') }}" class="btn btn-light">@lang('crud.cancel')</a>
</div>

@include('yindulacms::common.filepond_image')

resources/views/pages/_filepond.blade.php
@section('css')
    <link href="https://unpkg.com/filepond@^4/dist/filepond.css" rel="stylesheet" />
@endsection

@push('scripts')
    <script src="https://unpkg.com/filepond@^4/dist/filepond.js"></script>
    <script>
        // Set default FilePond options
        FilePond.setOptions({
            server: {
                process: "{{ config('filepond.server.process') }}",
                revert: "{{ config('filepond.server.revert') }}",
                headers: {
                    'X-CSRF-TOKEN': "{{ @csrf_token() }}",
                }
            }
        });

        // Create the FilePond instance
        FilePond.create(document.querySelector('input[name="image"]'));
        // FilePond.create(document.querySelector('input[name="filename[]"]'));
    </script>
@endpush

resources/views/pages/_show_fields.blade.php
<div class="col-md-6">
    <div class="row">

        <!-- Title Field -->
        <div class="form-group col-md-6">
            {!! Form::label('title', __('models/pages.fields.title') . ':') !!}
            <p>{{ $page->title }}</p>
        </div>


        @if ($page_setting && $page_setting->has_subtitle)
            <!-- Subtitle Field -->
            <div class="form-group col-md-6">
                {!! Form::label('subtitle', __('models/pages.fields.subtitle') . ':') !!}
                <p>{{ $page->subtitle }}</p>
            </div>
        @endif

        <!-- Author Id Field -->
        <div class="form-group col-md-6">
            {!! Form::label('author_id', __('models/pages.fields.author_id') . ':') !!}
            <p>{{ $page->author->name ?? '' }}</p>
        </div>

        <!-- Status Field -->
        <div class="form-group col-md-4">
            {!! Form::label('status', __('models/pages.fields.status') . ':') !!}
            <p>{{ $page->status }}</p>
        </div>

        <!-- Is Home Field -->
        <div class="form-group col-md-4">
            {!! Form::label('is_home', __('models/pages.fields.is_home') . ':') !!}
            <p>{{ $page->is_home }}</p>
        </div>

        <!-- Is Page Field -->
        <div class="form-group col-md-4">
            {!! Form::label('is_page', __('models/pages.fields.is_page') . ':') !!}
            <p>{{ $page->is_page }}</p>
        </div>

        <!-- Image Field -->
        <div class="form-group col-sm-12">
            <x-bazintemplate::image-component :src="$page->image_url" :alt="__('models/pages.fields.image')" />
        </div>
    </div>
</div>
<div class="col-md-6">

    @if ($page_setting && $page_setting->has_meta_description)
        <!-- Meta Description Field -->
        <div class="form-group col-md-12">
            {!! Form::label('meta_description', __('models/pages.fields.meta_description') . ':') !!}
            <p>{{ $page->meta_description }}</p>
        </div>
    @endif

    @if ($page_setting && $page_setting->has_meta_keywords)
        <!-- Meta Keywords Field -->
        <div class="form-group col-md-12">
            {!! Form::label('meta_keywords', __('models/pages.fields.meta_keywords') . ':') !!}
            <p>{{ $page->meta_keywords }}</p>
        </div>
    @endif

    @if ($page_setting && $page_setting->has_excerpt)
        <!-- Excerpt Field -->
        <div class="form-group col-md-12">
            {!! Form::label('excerpt', __('models/pages.fields.excerpt') . ':') !!}
            <p>{!! $page->excerpt !!}</p>
        </div>
    @endif

    @if ($page_setting && $page_setting->has_body)
        <!-- Body Field -->
        <div class="form-group col-md-12">
            {!! Form::label('body', __('models/pages.fields.body') . ':') !!}
            <p>{!! $page->body !!}</p>
        </div>
    @endif
</div>

resources/views/pages/_show_vertical_nav_pills.blade.php
{{-- <div class="row">
    <div class="col-12 col-sm-12 col-lg-12">
        <div class="card">
            <div class="card-header">

                {{-- <div class="section-header-breadcrumb">
                    <a href="{{ route('cms.features.create') }}" class="btn btn-primary form-btn">
                        @lang('crud.add_new') Section
                        <i class="fas fa-plus"></i>
                    </a>
                </div>

                <div class="section-header-breadcrumb">
                    <a href="{{ route('cms.features.create') }}" class="btn btn-primary form-btn">
                        @lang('crud.add_new') Feature
                        <i class="fas fa-plus"></i>
                    </a>
                </div>

             </div>
            <div class="card-body">
                <ul class="nav nav-pills" id="myTab3" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active show" id="sections-tab3" data-toggle="tab" href="#sections3"
                            role="tab" aria-controls="sections" aria-selected="true">Sections</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="features-tab3" data-toggle="tab" href="#features3" role="tab"
                            aria-controls="features" aria-selected="false">Features</a>
                    </li>
                </ul>
                <div class="tab-content" id="myTabContent2">
                    <div class="tab-pane fade active show" id="sections3" role="tabpanel"
                        aria-labelledby="sections-tab3">
                        <div class="row">


                        </div>
                    </div>
                    <div class="tab-pane fade" id="features3" role="tabpanel" aria-labelledby="features-tab3">
                        <livewire:yindulacms::features-table :page="$page" :key="time() . $page->id" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> --}}


<div class="row">
    <div class="col-12 col-sm-12 col-md-2">
        <ul class="nav nav-pills flex-column" id="myTab4" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="sections-tab4" data-toggle="tab" href="#sections4" role="tab"
                    aria-controls="sections" aria-selected="true">
                    Sections
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="features-tab4" data-toggle="tab" href="#features4" role="tab"
                    aria-controls="features" aria-selected="false">Features</a>
            </li>
        </ul>
    </div>
    <div class="col-12 col-sm-12 col-md-10">
        <div class="tab-content no-padding" id="myTab2Content">

            <div class="tab-pane fade show active" id="sections4" role="tabpanel" aria-labelledby="sections-tab4">
                <div class="row">
                    @include('yindulacms::feature_sections._show_horizontal_nav_pills')
                </div>
            </div>

            <div class="tab-pane fade" id="features4" role="tabpanel" aria-labelledby="features-tab4">
                @include('yindulacms::features._show_horizontal_nav_pills')
            </div>

        </div>
    </div>
</div>

resources/views/pages/create.blade.php
@extends('bazintemplate::layouts.authed')

@section('title')
    @lang('crud.add_new') @lang('models/pages.singular')
@endsection

@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">@lang('crud.add_new') @lang('models/pages.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('cms.pages.index') }}" class="btn btn-primary">@lang('crud.back')</a>
            </div>
        </div>
        <div class="content">
            @include('bazintemplate::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'cms.pages.store', 'files' => true]) !!}
                                    <div class="row">
                                        @include('yindulacms::pages._fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/datatables_actions.blade.php
<div class='btn-group'>
    <a href="{{ $showUrl }}" class='btn btn-primary btn-xs'>
        <i class="fa fa-list"></i>
    </a>
    <a href="{{ $editUrl }}" class='btn btn-secondary btn-xs'>
        <i class="fa fa-edit"></i>
    </a>
    <a class='btn btn-danger btn-xs' wire:click="deleteRecord({{ $recordId }})"
        onclick="confirm('Are you sure you want to remove this Record?') || event.stopImmediatePropagation()">
        <i class="fa fa-trash"></i>
    </a>

    <a class='btn btn-info btn-xs' wire:click="setHomePage({{ $homePageId }})" title="{{ __('Set Home Page') }}"
        onclick="confirm('Are you sure you want to update this Record?') || event.stopImmediatePropagation()">
        <i class="fa fa-home"></i>
    </a>
    <a class='btn btn-secondary btn-xs' wire:click="setEventPage({{ $eventPageId }})"
        title="{{ __('Set Event Page') }}"
        onclick="confirm('Are you sure you want to update this Record?') || event.stopImmediatePropagation()">
        <i class="fa fa-calendar"></i>
    </a>
    <a class='btn btn-info btn-xs' wire:click="setContactPage({{ $contactPageId }})"
        title="{{ __('Set Contact Page') }}"
        onclick="confirm('Are you sure you want to update this Record?') || event.stopImmediatePropagation()">
        <i class="fa fa-at"></i>
    </a>
</div>

resources/views/pages/edit.blade.php
@extends('bazintemplate::layouts.authed')

@section('title')
    @lang('yindulacms::crud.edit') @lang('yindulacms::models/pages.singular')
@endsection

@section('content')

    <section class="section">

        <div class="section-header">
            <h3 class="page__heading m-0">@lang('yindulacms::crud.edit') @lang('yindulacms::models/pages.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('cms.pages.index') }}" class="btn btn-primary">@lang('yindulacms::crud.back')</a>
            </div>
        </div>

        <div class="content">

            @include('bazintemplate::common.errors')

            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body ">

                                {!! Form::model($page, ['route' => ['cms.pages.update', $page->id], 'method' => 'patch', 'files' => true]) !!}
                                <div class="row">
                                    @include('yindulacms::pages._fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/index.blade.php
@extends('bazintemplate::layouts.authed')

@section('title')
    @lang('yindulacms::models/pages.plural')
@endsection

@section('content')
    <section class="section">

        <div class="section-header">

            <h1>@lang('yindulacms::models/pages.plural')</h1>

            <div class="section-header-breadcrumb">
                <a href="{{ route('cms.pages.create') }}" class="btn btn-primary form-btn">
                    @lang('yindulacms::crud.add_new')
                    <i class="fas fa-plus"></i>
                </a>
            </div>
        </div>

        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    <livewire:yindulacms::pages-table />
                </div>
            </div>
        </div>

    </section>
@endsection

resources/views/pages/show.blade.php
@extends('bazintemplate::layouts.authed')

@section('title')
    @lang('yindulacms::models/pages.singular') @lang('yindulacms::crud.details')
@endsection

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>@lang('yindulacms::models/pages.singular')
                @lang('yindulacms::crud.details')
            </h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('cms.pages.index') }}" class="btn btn-primary form-btn float-right">
                    @lang('yindulacms::crud.back')
                </a>
                <a href="{{ route('cms.pages.edit', $page->id) }}" class="btn btn-secondary form-btn">
                    {{-- @lang('yindulacms::crud.edit') --}}
                    <i class="fa fa-edit"></i>
                </a>
                <a href="{{ route('cms.pages.create') }}" class="btn btn-primary form-btn">
                    <i class="fas fa-plus"></i>
                </a>
                <a href="{{ route('cms.pageSettings.createOrEdit', ['pageId' => $page->id]) }}"
                    class="btn btn-secondary form-btn">
                    <i class="fas fa-cogs"></i>
                </a>
            </div>
        </div>

        @include('bazintemplate::common.errors')

        <div class="section-body">
            <div class="card">
                <div class="card-body">

                    <div class="row">
                        @include('yindulacms::pages._show_fields')
                    </div>
                    @include('yindulacms::pages._show_vertical_nav_pills')

                </div>
            </div>
        </div>

    </section>
@endsection

@push('page_js')
    <script type="importmap">
    {
      "imports": {
        "@popperjs/core": "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js",
        "bootstrap": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.esm.min.js"
      }
    }
    </script>


    <script type="module">
        import {
            Modal
        } from 'bootstrap';

        document.addEventListener('livewire:init', () => {
            Livewire.on('closeModal', ({
                modalId
            }) => {
                const modalsElement = document.querySelector(modalId)
                let modal = Modal.getInstance(modalsElement);

                modal.hide()
            })

            let modalsElement = document.querySelector('#productForm');

            modalsElement.addEventListener('hidden.bs.modal', () => {
                Livewire.dispatch('resetModal');
            });
        })
    </script>
@endpush